package app

import (
	"github.com/gin-gonic/gin"
	"github.com/srcndev/message-service/pkg/middleware"

	_ "github.com/srcndev/message-service/docs" // docs is generated by Swag CLI
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// setupRouter configures all HTTP routes
func (a *App) setupRouter() {
	router := gin.Default()

	// Global error handler middleware
	router.Use(middleware.ErrorHandler())

	// Health check route (outside versioned API)
	a.container.HealthHandler.RegisterRoutes(&router.RouterGroup)

	// API Documentation - Swagger UI
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// Redirect /docs to /swagger for backward compatibility
	router.GET("/docs", func(c *gin.Context) {
		c.Redirect(302, "/swagger/index.html")
	})

	// API v1 routes
	v1 := router.Group("/api/v1")
	{
		a.container.MessageHandler.RegisterRoutes(v1)
		a.container.SenderHandler.RegisterRoutes(v1)
	}

	a.router = router
}
